name: fools
description: Fools start.
version: 1.0.1
repository: https://github.com/FoolScript/fools-cli

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  fools: